apiVersion: apps/v1

kind: Deployment 

metadata:
  name: med-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicamento
  template:
    metadata:
      labels:
        app: medicamento
    spec:
      containers:
        - name: medicamento
          image: joaosantos7293/medicamento
          resources:
            requests:
              memory: "64mi"
              cpu: "250m"
            limits:
              memory: "128mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: med-clusterip-service
spec:
  selector:
    app: medicamento
  ports:
   - name: medicamento
     protocol: TCP
     port: 2000
     targetPort: 2000