apiVersion: apps/v1

kind: Deployment 

metadata:
  name: usuario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario
  template:
    metadata:
      labels:
        app: usuario
    spec:
      containers:
        - name: usuario
          image: joaosantos7293/usuarios
          resources:
            requests:
              memory: "64mi"
              cpu: "250m"
            limits:
              memory: "128mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: usuario-clusterip-service
spec:
  selector:
    app: usuario
  ports:
   - name: usuario
     protocol: TCP
     port: 1000
     targetPort: 1000